name: "CI"

on:
  push:

jobs:
  component-tests:
    name: Run Component Tests 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js | Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Component Tests
        run: npm run test

  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    outputs:
      app: app/build/outputs/apk/debug
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Download and Create Android Emulator Image
        run: |
          $ANDROID_HOME/tools/bin/sdkmanager --install "system-images;android-29;google_apis;x86"
          $ANDROID_HOME/tools/bin/avdmanager create avd --force -n TestEmulator -d pixel --package 'system-images;android-29;google_apis;x86'
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Install dependencies
        run: npm install

      - name: Set Gradlew Permissions
        run: chmod +x android/gradlew

      - run: cd android && ./gradlew assembleDebug
      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_API_KEY }}
          project-id: ${{ secrets.MAESTRO_PROJECT_ID }}
          app-file: android/app/build/outputs/apk/debug/app-debug.apk