name: "CI"

on:
  push:

jobs:
  component-tests:
    name: Run Component Tests 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js | Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Component Tests
        run: npm run test
